### ISSUE TITLE
can we have hostNetwork enable option for redis cluster here?

### ISSUE THREAD

**Issue by salla2** [ucloud/redis-operator#10]

**Comment by simonhou** [comment]
I have  the same requirement. We need to enable hostnetwork, and modify the port number to enable multi instance deployed in one node.

**Comment by polefishu** [comment]
Hi @simonhou 

It's not implemented at the moment.

If you want to send a PR with this, we'll be happy to add it. We can help you and guide you trough the process.

**Comment by simonhou** [comment]
@polefishu That is great, could you  provide me the guide? Or we can talk with webchat.
