### ISSUE TITLE
Resizing cluster doesn't resize sentinel statefulset

### ISSUE THREAD

**Issue by promolic1** [ucloud/redis-operator#14]
I have been using your operator since a couple of weeks without issues

Until yesterday, it was just fine, but during the troubleshooting I decided to resize the cluster and see if this would help somehow.

As the documentation says, I modified the RedisCluster resource to 5 nodes. The cluster resized, but the number of sentinel instances is at 3 and isn't changing.

According to the features given for this operator, the number of worker nodes scales with the number of sentinel nodes, and this isn't happening.

Any workaround? It's safe to scale the statefulset to 5?

Thanks for reading

**Comment by polefishu** [comment]
resize the `.spec.sentinel.replicas`, after changing the configuration, you can safely scale the  sentinel statefulset.

**Comment by promolic1** [comment]
Hello again.
Sorry for opening again, I forgot to reply to the issue but your solution seems to be working so far.

As you suggested, and to be clearer if someone finds this later, you should add this configuration to the `redisclusters.redis.kun` object that manages your cluster.

Thank you for answering.
