### ISSUE TITLE
Ignore slave whose runid begin with "fake_slave_"

### ISSUE THREAD

**Issue by lixiaojun629** [ucloud/redis-operator#6]
We need to synchronize data in redis instances across multiple regions, so we developed a program as a fake slave node of master in region A. The fake slave fetch RDB file and subsequent commands from the master redis in region A, and then parse RDB into redis commands and execute them on redis in region B to achieve the purpose of cross-region synchronization. 

As described above, we need redis sentinels in region A to ignore the fake slave  when checking the count  and status of the slaves, and we make the fake slave runid begin with "fake_slave_" for easily filter out. Thanks.

**Comment by polefishu** [comment]
Redis is not allowed to configure runid, we think `slave-priority` can be used to identify a particular slave, a special priority of 0 marks the slave as not able to perform the role of master, so a slave with priority of 0 will never be selected by Redis Sentinel for promotion.
Operator mange slave with `slave-priority = 1`,  you can run a fake slave with  `slave-priority = 0`, then operator will not care about this slave with `slave-priority = 0`.

**Comment by lixiaojun629** [comment]
OK. Thank you.
